# https://circleci.com/docs/2.0/sample-config/
# https://circleci.com/docs/2.0/language-java-maven/
version:                 2.1
jobs:
  build:
     working_directory:  ~/avaeroh.github.io/tests/API # directory where steps will run

     docker:
       - image:          circleci/openjdk:8-jdk-stretch

     steps:
       - checkout
       - run:            ls -la
       - run:            pwd
       # - run:          cd ~/avaeroh.github.io/tests/API
       # - restore_cache:  # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
       #    key:           avaeroh.github.io-{{ checksum "tests/API/pom.xml" }}
       # - run:            ls -la
       # - run:            pwd

       # - run:            mvn dependency:go-offline # gets the project dependencies

       # - save_cache:     # saves the project dependencies
       #    paths:
       #      - ~/.m2
       #    key:           avaeroh.github.io-{{ checksum "tests/API/pom.xml" }}

       - run:            mvn clean verify

 # testcafe:
 #    docker:
 #      # testcafe
 #      - image:         testcafe/testcafe
 #    steps:
 #      - checkout
 #      - run:           testcafe chrome tests/UI/tests.js

# workflows:
#   version:             2.1
#   test:
#     jobs:
#       - api_test
#       - testcafe


# version:               2
# jobs:
#   build:
#     docker:
#       - image:         ubuntu:latest
#
#     steps:
#       - checkout
#       - run:           apt install mvn
#       - run:           apt install npm
#       - run:           mvn -f .tests/API clean verify
#       - run:           npm install -g testcafe
#       - run:           testcafe chrome tests/UI/tests.js



# version:               2.1
# orbs:
#   maven:               circleci/maven@1.0.0
# workflows:
#   maven_test:
#     jobs:
#       - maven/test:
#           command:     '-X verify'
