version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14-browsers

    steps:
      - checkout
      - run: mvn -f .tests/API clean verify
      - run: sudo npm install -g testcafe
      - run: testcafe chrome tests/UI/tests.js
